// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf2RwnRjD1Hu_33K92LCF_PEG6ZvGVRQ4',
    appId: '1:361911417073:web:c8610ecd4c9e56d161d150',
    messagingSenderId: '361911417073',
    projectId: 'nexazan',
    authDomain: 'nexazan.firebaseapp.com',
    storageBucket: 'nexazan.firebasestorage.app',
    measurementId: 'G-R7PEL6P7H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQrc30duQTLJbtzIoaqerLs0pDgLLZ9zM',
    appId: '1:361911417073:android:941930c895e7e46661d150',
    messagingSenderId: '361911417073',
    projectId: 'nexazan',
    storageBucket: 'nexazan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChZHtcUvNvngTDnTFNZ7hsgmybav6K3bc',
    appId: '1:361911417073:ios:c5a41ffd5de5690561d150',
    messagingSenderId: '361911417073',
    projectId: 'nexazan',
    storageBucket: 'nexazan.firebasestorage.app',
    iosBundleId: 'com.example.testLiveAzan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChZHtcUvNvngTDnTFNZ7hsgmybav6K3bc',
    appId: '1:361911417073:ios:c5a41ffd5de5690561d150',
    messagingSenderId: '361911417073',
    projectId: 'nexazan',
    storageBucket: 'nexazan.firebasestorage.app',
    iosBundleId: 'com.example.testLiveAzan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf2RwnRjD1Hu_33K92LCF_PEG6ZvGVRQ4',
    appId: '1:361911417073:web:47d4f218891a8b5a61d150',
    messagingSenderId: '361911417073',
    projectId: 'nexazan',
    authDomain: 'nexazan.firebaseapp.com',
    storageBucket: 'nexazan.firebasestorage.app',
    measurementId: 'G-5Q1K7S2MVK',
  );
}
